# Generated by Django 3.0.4 on 2020-03-17 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScovilleScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pepper_name', models.CharField(max_length=100)),
                ('heat_range', models.CharField(max_length=100)),
                ('image', models.FilePathField(path='/img')),
            ],
            options={
                'verbose_name': 'ScovilleScale',
                'verbose_name_plural': 'ScovilleScales',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('tolerance', models.CharField(max_length=100)),
                ('image', models.FilePathField(path='/img')),
                ('video', models.CharField(max_length=255)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scovilleapp.Profile')),
                ('scoville_scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scovilleapp.ScovilleScale')),
            ],
            options={
                'verbose_name': 'BlogPost',
                'verbose_name_plural': 'BlogPosts',
            },
        ),
    ]
